/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uaspbo;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author Careen Emilza
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLOG = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUSN = new javax.swing.JLabel();
        lblPW = new javax.swing.JLabel();
        txtUSN = new javax.swing.JTextField();
        pwfPWD = new javax.swing.JPasswordField();
        btnSH = new javax.swing.JButton();
        btnLOG = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        lblREG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlLOG.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("LOGIN");

        lblUSN.setText("USERNAME");

        lblPW.setText("PASSWORD");

        btnSH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSH.setText("SHOW");
        btnSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSHActionPerformed(evt);
            }
        });

        btnLOG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLOG.setText("LOGIN");
        btnLOG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLOGActionPerformed(evt);
            }
        });

        lbl1.setText("Belum Mempunyai Akun?");

        lblREG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblREG.setText("REGISTRASI");
        lblREG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblREGMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlLOGLayout = new javax.swing.GroupLayout(pnlLOG);
        pnlLOG.setLayout(pnlLOGLayout);
        pnlLOGLayout.setHorizontalGroup(
            pnlLOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLOGLayout.createSequentialGroup()
                .addGroup(pnlLOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLOGLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel1))
                    .addGroup(pnlLOGLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(pnlLOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUSN)
                            .addComponent(lblPW))
                        .addGap(42, 42, 42)
                        .addGroup(pnlLOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUSN)
                            .addComponent(pwfPWD, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnSH))
                    .addGroup(pnlLOGLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(pnlLOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLOG)
                            .addComponent(lbl1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblREG)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlLOGLayout.setVerticalGroup(
            pnlLOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLOGLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(pnlLOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUSN)
                    .addComponent(txtUSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlLOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPW)
                    .addComponent(pwfPWD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSH))
                .addGap(18, 18, 18)
                .addComponent(btnLOG)
                .addGap(18, 18, 18)
                .addGroup(pnlLOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(lblREG))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLOG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLOG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLOGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLOGActionPerformed
        if (txtUSN.getText().isEmpty() || String.valueOf(pwfPWD.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harap isi username dan password terlebih dahulu.");
        } else {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("UasPboPU");
            EntityManager em = emf.createEntityManager();

            try {
                em.getTransaction().begin();

                String username = txtUSN.getText();
                String password = String.valueOf(pwfPWD.getPassword());

                Datalogin dataLogin = em.find(Datalogin.class, username);

                if (dataLogin == null) {
                    JOptionPane.showMessageDialog(null, "Username tidak ditemukan.");
                    txtUSN.requestFocus();
                } else if (dataLogin.getPassword().equals(password)) {
                    JOptionPane.showMessageDialog(null, "Selamat datang!");
                    DataMhs p = new DataMhs();
                    p.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Password salah!");
                }

                em.getTransaction().commit();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + ex.getMessage());
                ex.printStackTrace();
            } finally {
                em.close();
                emf.close();
            }
        }
    }//GEN-LAST:event_btnLOGActionPerformed

    private void lblREGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblREGMouseClicked
        RegistFrame yes = new RegistFrame();
        yes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblREGMouseClicked

    private void btnSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSHActionPerformed
        if ("SHOW".equals(btnSH.getText())) {
            pwfPWD.setEchoChar((char) 0); // Menampilkan password
            btnSH.setText("HIDE"); // Mengubah teks tombol menjadi HIDE
        } else {
            pwfPWD.setEchoChar('*'); // Menyembunyikan password
            btnSH.setText("SHOW"); // Mengubah teks tombol kembali ke SHOW
        }
    }//GEN-LAST:event_btnSHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLOG;
    private javax.swing.JButton btnSH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lblPW;
    private javax.swing.JLabel lblREG;
    private javax.swing.JLabel lblUSN;
    private javax.swing.JPanel pnlLOG;
    private javax.swing.JPasswordField pwfPWD;
    private javax.swing.JTextField txtUSN;
    // End of variables declaration//GEN-END:variables
}
