/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uaspbo;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author Careen Emilza
 */
public class RegistFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegistFrame
     */
    public RegistFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        pnlREG = new javax.swing.JPanel();
        lblREG = new javax.swing.JLabel();
        lblUSN = new javax.swing.JLabel();
        lblPW = new javax.swing.JLabel();
        txtUSN = new javax.swing.JTextField();
        btnREG = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        lblLOG = new javax.swing.JLabel();
        txtPW = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlREG.setBackground(new java.awt.Color(153, 153, 153));

        lblREG.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblREG.setText("REGISTRASI");

        lblUSN.setText("USERNAME");

        lblPW.setText("PASSWORD");

        btnREG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnREG.setText("REGIST");
        btnREG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREGActionPerformed(evt);
            }
        });

        lbl1.setText("Sudah Mempunyai Akun?");

        lblLOG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLOG.setText("LOGIN");
        lblLOG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLOGMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlREGLayout = new javax.swing.GroupLayout(pnlREG);
        pnlREG.setLayout(pnlREGLayout);
        pnlREGLayout.setHorizontalGroup(
            pnlREGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlREGLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlREGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUSN)
                    .addComponent(lblPW))
                .addGap(23, 23, 23)
                .addGroup(pnlREGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUSN, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(txtPW))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlREGLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(pnlREGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlREGLayout.createSequentialGroup()
                        .addComponent(btnREG)
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlREGLayout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLOG)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlREGLayout.createSequentialGroup()
                        .addComponent(lblREG)
                        .addGap(109, 109, 109))))
        );
        pnlREGLayout.setVerticalGroup(
            pnlREGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlREGLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblREG)
                .addGap(39, 39, 39)
                .addGroup(pnlREGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUSN)
                    .addComponent(txtUSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlREGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPW)
                    .addComponent(txtPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnREG)
                .addGap(18, 18, 18)
                .addGroup(pnlREGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(lblLOG))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlREG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlREG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnREGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREGActionPerformed
        if (txtUSN.getText().equals("") || txtPW.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap Isi Semua Data.");
        } else {
            String username, password;
            username = txtUSN.getText();
            password = txtPW.getText();

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("UasPboPU");
            EntityManager em = emf.createEntityManager();
            em.getTransaction().begin();

            Datalogin existingUser = em.find(Datalogin.class, username);

            if (existingUser != null) {
                JOptionPane.showMessageDialog(null, "Username sudah terdaftar. Gunakan username lain.");
                txtUSN.requestFocus();
            } else {
                // Validasi password menggunakan metode
                String passwordError = validatePassword(password);
                if (passwordError != null) {
                    JOptionPane.showMessageDialog(null, passwordError);

                } else {
                    Datalogin newUser = new Datalogin();
                    newUser.setUsername(username);
                    newUser.setPassword(password);

                    em.persist(newUser);

                    em.getTransaction().commit();
                    JOptionPane.showMessageDialog(null, "Sign Up berhasil");

                    LoginFrame loginFrame = new LoginFrame();
                    loginFrame.setVisible(true);
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_btnREGActionPerformed

    private void lblLOGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLOGMouseClicked
        LoginFrame yes = new LoginFrame();
        yes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLOGMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistFrame().setVisible(true);
            }
        });
    }

    private String validatePassword(String password) {
        if (password.length() < 8) {
            return "Password minimal 8 karakter.";
        }
        if (!password.matches(".*[_!@#$%^&(),.?\\\":{}|<>]*.")) {
            return "Password harus mengandung minimal satu simbol.";
        }
        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnREG;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lblLOG;
    private javax.swing.JLabel lblPW;
    private javax.swing.JLabel lblREG;
    private javax.swing.JLabel lblUSN;
    private javax.swing.JPanel pnlREG;
    private javax.swing.JTextField txtPW;
    private javax.swing.JTextField txtUSN;
    // End of variables declaration//GEN-END:variables
}
